#spring:
#  jpa:
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    hibernate:
#      ddl-auto: create-drop
#  datasource:
#    url: jdbc:postgresql://localhost:5432/platform
#    username: postgres
#    password: postgres
#    initialization-mode: always