spring:
  port: 8080
  application:
    name: stdstack-course-service
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0

  cloud:
    gcp:
      sql:
        database-name: stdtest
        instance-connection-name: stdstack:europe-west2:std-stack-base

management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"

logging:
  level:
    root: info
